### ISSUE TITLE
NEI Recipe Check Crash

### ISSUE THREAD

**Issue by SirWoofie** [Chicken-Bones/NotEnoughItems#303] opened 2015-11-20 03:22 UTC
I just started this pack of my own, quite unstable, and it seems that NEI and it's recipe worker(dunno what its name actually is) are acting up, as I cannot check recipes anymore. This has happened a few times now, and trying to recreate this is way too much work, to be honest. The log says something about the RecipeHandler and Inventory Manager/GUI Manager, so it might be a problem with the switching of inventory screens. If there is a fix out for this, or if i should downgrade to a different NEI version, please let me know. Thanks!
Side note: I have the near maximum amount of IDs possible right now-4000 or so IDs, if it makes a difference.
Extra: It appears that this person also is having the same sort of problem I am.
https://github.com/Chicken-Bones/NotEnoughItems/issues/273

[NEI Related Crashlog.txt](https://github.com/Chicken-Bones/NotEnoughItems/files/39728/NEI.Related.Crashlog.txt)
[Full Crashlog- Nei Related.txt](https://github.com/Chicken-Bones/NotEnoughItems/files/39729/Full.Crashlog-.Nei.Related.txt)

**Comment by Chicken-Bones** [comment] 2015-11-22 07:30
Report to mariculture plugin dev?

**Comment by SirWoofie** [comment] 2015-11-23 02:38
Thanks! Will do.

**Comment by vagaprime** [comment] 2015-11-29 22:32
I do not think it is Mariculture. I have just recently started to get a crash in my modpack when looking up the recipes and uses for items after updating Pam's harvestcraft

**Comment by Chicken-Bones** [comment] 2015-12-13 03:16
Need a full FML log for that one.

**Comment by vagaprime** [comment] 2015-12-13 03:36
here is the fml log

http://pastebin.com/NuwpNrtq

**Comment by Chicken-Bones** [comment] 2015-12-25 11:30
Surprisingly, that doesn't provide me with any more information.
`java.lang.NullPointerException
        at net.minecraft.crash.CrashReportCategory.func_85069_a(CrashReportCategory.java:145) ~[k.class:?]`
doesn't actually tell me what's happening. I'm going to close this, feel free to post if you get any more info, and I'll open a new issue if we can identify the cause

**Closed by Chicken-Bones** 2015-12-25 11:30 UTC

**Comment by SvEgiiVEteR** [comment] 2016-03-05 09:29
@Chicken-Bones 
@vagaprime 
1 crash breaking due to mod
MB_Battlegear2-Bullseye
2 normal crash
http://pastebin.com/pph7cz9w
