### ISSUE TITLE
Fatal Crash - Updating Screen Event

### ISSUE THREAD

**Issue by Tim020** [Chicken-Bones/NotEnoughItems#179] opened 2015-04-03 19:16 UTC
Entire game crashes when trying to add more items from NEI to your Inventory than the player has space for (I.e giving 3 stacks when only have room for 2)
Running the DW20 FTB 1.7.10 pack, version 1.2.1
Full crash log here: http://pastebin.com/3WY2d7JK

**Comment by Chicken-Bones** [comment] 2015-04-04 12:31
Duplicate of #153

**Closed by Chicken-Bones** 2015-04-04 12:31 UTC
